import os

# SIMULATION SETTINGS
SIMULATION_DURATION_DAYS = 14
DAILY_MESSAGE_LIMIT = 80
MESSAGES_PER_SESSION = 3

# ACCOUNT SETTINGS - UPDATE THESE!
INSTAGRAM_USERNAME = "lulucats2015"  # Change this
PARTNER_USERNAME = "victorhallo12"  # Change this

# LOCAL AI SETTINGS (Ollama)
OLLAMA_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama2:latest"

# PERSISTENCE
STATE_FILE = "data/simulation_state.pkl"
BACKUP_INTERVAL = 5

# ERROR HANDLING
MAX_RETRIES = 3
RETRY_DELAYS = [5, 15, 30]